# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34d8e7436b51c820adc785e3a3453fa31c14863d2e7909b75055221df15ce8d81ec222a8e8fe4d3c3f7ab3d15c56320e62d72eae381dab4ed0c1854b396003bb

test:
  secret_key_base: c7083a35aaad229665b9867c1636340c3bf2918cc8b00b8e26a07ca7ed4c355e74dfefa6bea953ca4f3c050c76c6b9a1134afc7a36e1e361425a7e13de544275

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
